export const IJM_EVENTS = {
    PEER_JOINED:"PEER_JOINED",
    PEER_LEFT:"PEER_LEFT",
    PEER_UPDATED:"PEER_UPDATED",
    DEVICE_UPDATED:"DEVICE_UPDATED",
    DOMINANT_SPEAKER:"DOMINANT_SPEAKER",
    NETWORK_QUALITY:"NETWORK_QUALITY"
  
  }